= Getting started

== Installation

Before start you should add dependency to your Java-based project. For Gradle build system add:
[source,groovy]
repositories {
    jcenter()
}
dependencies {
    compile 'com.eztexting:eztexting-api-client:1.0.0'
}

for Maven build add following lines to your pom xml:
[source,xml]
<!-- callfire maven repo -->
<repositories>
    <repository>
        <id>callfire-com</id>
        <name>callfire-com</name>
        <url>http://dl.bintray.com/callfire-com/maven</url>
    </repository>
</repositories>
<!-- dependency -->
<dependencies>
    <dependency>
        <groupId>com.eztexting</groupId>
        <artifactId>eztexting-api-client</artifactId>
        <version>1.0.0</version>
    </dependency>
</dependencies>

After these steps *eztexting-api-client* should appear in your project dependencies along with other transitive ones.

In case you want to build it yourself:
[source]
    $ git clone https://github.com/CallFire/eztexting-api-client-java.git
    $ cd eztexting-api-client-java
    $ gradlew build clientFatJar

it will create 4 jars in *build/libs* directory:
[source]
    eztexting-api-client-X.Y.Z.jar
    eztexting-api-client-X.Y.Z-all.jar - client jar with all dependencies inside
    eztexting-api-client-X.Y.Z-javadoc.jar
    eztexting-api-client-X.Y.Z-sources.jar


== Overview
To create client instance just provide API login and password. API credentials should be configured on account page.
Client uses HTTPS connection.

Example how to get account information using client:
[source,java]
public class TestEzTextingApi {
    public static void main(String[] args) {
        EzTextingClient client = new EzTextingClient("api_login", "api_password");

    }
}

.*List of API classes:*
[source,java]
    EzTextingClient client = new EzTextingClient("api_login", "api_password");
    client.messagingApi();


== Error handling
The EzTexting Developers API uses standard HTTP response codes for responses. These HTTP codes indicate whether
 or not an API operation is successful.

Status Code 200 is the desired response code. A standard JSON response will follow.

Codes in the 400s range detail all of the errors a EzTexting Developer could encounter while using the API. Bad
 Request, Rate Limit Reached, and Unauthorized are some of the sorts of responses in the 400s block.

Codes in the 500s range are error responses from the EzTexting system. If an error has occurred anywhere in the
 execution of a resource that was not due to user input, a 500 response will be returned with a corresponding
 JSON error body. In that body will contain a message detailing what went wrong.

.All API methods throw following exceptions (all are RuntimeException):
 * *EzTextingClientException* - in case error has occurred in client
 * *EzTextingApiException* - in case API cannot be queried for some reason and server returned error (this is the base
 exception for API errors, some specific HTTP codes have their own exception):
 ** *400 - BadRequestException* - The request was formatted improperly
 ** *401 - UnauthorizedException* - API Key missing or invalid
 ** *403 - AccessForbiddenException* - Insufficient permissions
 ** *404 - ResourceNotFoundException* - The resource requested does not exist
 ** *500 - InternalServerErrorException* - We had an error! Sorry about that.
 ** other error codes will throw EzTextingApiException

*EzTextingApiException* has *errors* property with details why errors has occurred.


== Debug & logging
In case you want to see requests/responses which client sends/receives from EzTexting platform you should set *DEBUG*
level for *com.eztexting* package, then you'll see something like that in your logs:
[source]
2015/11/21 19:02:47:355 EEST [DEBUG] RestApiClient - GET request to https://app.eztexting.com/incoming-messages/123?format=json with params: User=winnie&Password=the-pooh
2015/11/21 19:02:48:722 EEST [DEBUG] RestApiClient - received entity
{
	"Response":{
		"Status":"Success",
		"Code":200,
		"Entry": {
			"TYPE":SMS,
			"ID":123,
			"PhoneNumber":"3312943691",
			"Subject":"",
			"Message":"test",
			"New":"0",
			"FolderID":"13",
			"ContactID":"",
			"ReceivedOn":"10-04-2012 9:06 AM"
		}
	}
}

If you don't have any logger implementation in classpath you can simply use
commons-logging SimpleLog which are shipped with EzTexting client. See example of usage below:
[source,java]
System.setProperty("org.apache.commons.logging.Log", "org.apache.commons.logging.impl.SimpleLog");
System.setProperty("org.apache.commons.logging.simplelog.showdatetime", "true");
System.setProperty("org.apache.commons.logging.simplelog.log.com.eztexting", "DEBUG");
